# Generated by Django 2.2.2 on 2019-06-27 08:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20190627_0851'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EducationalForm',
        ),
    ]
