# Generated by Django 2.2.2 on 2019-06-27 09:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_delete_educationalform'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='parent_father',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parent_father', to='api.Parent', verbose_name='Папа'),
        ),
        migrations.AddField(
            model_name='account',
            name='parent_mother',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parent_mother', to='api.Parent', verbose_name='Мама'),
        ),
    ]
