# Generated by Django 2.2.3 on 2019-07-01 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20190701_1700'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='login',
            field=models.CharField(default=1, max_length=255, verbose_name='Логин'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='account',
            name='password',
            field=models.CharField(default=1, max_length=255, verbose_name='Пароль'),
            preserve_default=False,
        ),
    ]
